### PR TITLE
Changed color of Generate button as instructed

### LINKED ISSUE #15: ISSUE-005: Button Change Color
Describe the issue
Change the color of the button to be #A1BEEA

### PR DESCRIPTION
**Pull request by Virtual4087**
# Description of the issue
  Fixes #15  
# Description of the fix
  Changed the color of the button to #A1BEEA

### CODE REVIEW

**Comment by anavatya** [comment]
@Virtual4087 I merged the other PR, due to which there is a conflict, can you please resolve that ? Will merge after that.

**Review by Virtual4087 — COMMENTED** [review]
Ok I'm on it

**Comment by Virtual4087** [comment]
Should work now

**Review by anavatya — APPROVED** [review]
LGTM

**Pull request merged**
